### ISSUE TITLE
Generate the date dynmically when creates or update a Property

### ISSUE THREAD

**Issue by arnaugarcia** [Uplace/uplace.es#44]
Estaría guay que cuando se haga un POST se actualice el campo de created y se ponga la fecha actual y cuando se haga un PUT se actualice el campo updated con la fecha actual.

**Comment by arnaugarcia** [comment]
Al igual que cuando se haga un PATCH (Feature que implementaré hoy XD)

**Comment by arnaugarcia** [comment]
Correcto, pero hay un campo que se llama updated, a ese me refiero

**Comment by NicosFabro** [comment]
Ah vale

**Comment by arnaugarcia** [comment]
Cierro esta issue y elimino la rama

**Comment by NicosFabro** [comment]
¿Ya has hecho esto del date?

**Comment by arnaugarcia** [comment]
DAAAAM NO!

**Comment by arnaugarcia** [comment]
Había leído reference XD

**Comment by NicosFabro** [comment]
Hahaha ya decía yo

**Comment by arnaugarcia** [comment]
Cierro esto y lo continuamos en #54
