### ISSUE TITLE
Generate reference randomly on create some entity (Apartment, Office, Bussiness)

### ISSUE THREAD

**Issue by arnaugarcia** [Uplace/uplace.es#9]
Instrucciones para el tema de las referencias (Te recomiendo que cada vez que **hable de un fichero** o un **_método_** lo abras/busques para tener en mente el workflow):

Para hacerlo lo mas limpio posible, lo mejor es crear en el **PropertyService** un método **_generateReference()_** y que este llame a **PropertyRepository** y haga el **_findByReference(String reference)_**. Si lo haces en el **ApartmentService** y llamas al **PropertyRepository** cuando tengas que hacer lo en Hotel, Business, Terrain o alguna Entity heredada vas a tener que copiar y pegar código, cuando si lo haces en el PropertyService que es el  "Service padre" y lo llamas desde los Resources (**ApartmentResource**, **BuldingResource**) reutilizas código y no tienes que hacer un **_generateReference()_** para cada Service de una Entity heredada.

Quedaría así:

- AparmentResource -> _propertyService_.generateReference();

Y no:
- AparmentResource -> _apartmentService_.generateReference();

Espero que se haya entendido XD

Intenta hacer los commits y si no lo has pillado el miércoles lo miramos y te lo explico bien

Saap!

**Comment by arnaugarcia** [comment]
Instrucciones para el tema de las referencias (Te recomiendo que cada vez que hable de un fichero o un método lo abras/busques para tener en mente el workflow):Para hacerlo lo mas limpio posible, lo mejor es crear en el PropertyService un método generateReference() y que este llame a PropertyRepository y haga el findByReference(String reference). Si lo haces en el ApartmentService y llamas al PropertyRepository cuando tengas que hacer lo en Hotel, Business, Terrain o alguna Entity heredada vas a tener que copiar y pegar código, cuando si lo haces en el PropertyService que es el "Service padre" y lo llamas desde los Resources (ApartmentResource, BuldingResource) reutilizas código y no tienes que hacer un generateReference()para cada Service de una Entity heredada.Quedaría así:AparmentResource -> propertyService.generateReference();Y no:AparmentResource -> apartmentService.generateReference();Espero que se haya entendido XDIntenta hacer los commits y si no lo has pillado el miércoles lo miramos y te lo explico bienSaap!
--

**Comment by arnaugarcia** [comment]
Instrucciones para el tema de las referencias (Te recomiendo que cada vez que **hable de un fichero** o un **_método_** lo abras/busques para tener en mente el workflow):

Para hacerlo lo mas limpio posible, lo mejor es crear en el **PropertyService** un método **_generateReference()_** y que este llame a **PropertyRepository** y haga el **_findByReference(String reference)_**. Si lo haces en el **ApartmentService** y llamas al **PropertyRepository** cuando tengas que hacer lo en Hotel, Business, Terrain o alguna Entity heredada vas a tener que copiar y pegar código, cuando si lo haces en el PropertyService que es el  "Service padre" y lo llamas desde los Resources (**ApartmentResource**, **BuldingResource**) reutilizas código y no tienes que hacer un **_generateReference()_** para cada Service de una Entity heredada.

Quedaría así:

- AparmentResource -> _propertyService_.generateReference();

Y no:
- AparmentResource -> _apartmentService_.generateReference();

Espero que se haya entendido XD

Intenta hacer los commits y si no lo has pillado el miércoles lo miramos y te lo explico bien

Saap!

**Comment by NicosFabro** [comment]
Ok! Este mediodía pruebo de hacerlo.
